### ISSUE TITLE
calling Parser.consume() from a callback does not clear jsonByteStream

### ISSUE THREAD

**Issue by martin-tauber** [jahnestacado/chunk2json#2]
```
var a='{"a":"abc"}';
var b='{"b":"def"}';

var p = new Parser();
p.on('json', (json) => {
    console.log(json.toString());
    p.consume(b);
}

p.consume(a);

// {"a": "abc"}
// {"a": "abc"}{"b":"def"} <= in the second output I still receive the first part of the consume!!!

```
I quickly wrote this example because it represents what I experianced while using the lib in my code. Basically when calling Parser.consume() from within the callback the jsonByteStream is not cleared and therefor with the second Parser.consume() I receive the first json as well.

Hope this helps
Regards

**Comment by jahnestacado** [comment]
The `consume` function is not supposed to be called from within the `.on("json")` callback. By calling it from within the callback it will result in an infinite loop which should throw the `Maximum call stack size exceeded` error.

Currently this is not the case and the code needs to be adjusted as such
``` javascript
Parser.prototype._extractJSON = function(){
    var parser = this;
    var jsonByteStream = parser.jsonByteStream;
    parser.jsonByteStream = new Array();
    parser.currentIndex = 0;
    parser._eventHandlers.json.forEach(function(cb){
        cb(new Buffer(jsonByteStream));
    });    
};
```

To summarize, the way that you used the `consume` function is not the intended one and it won't work properly. But it should also throw the right error and make clear to the developer what is going wrong. Which is not currently the case. 

I will do this change asap and release a new version of the module.

Moreover I would like to understand why you are calling the `consume` function from within the `json` callback.

Mainly the `consume` function should be used to process incoming chunks (e.g from a TCP connection) and the module internally will try to assemble them and when it detects a complete JSON object it will call the callback.

**Comment by martin-tauber** [comment]
hm -  now that you mention it.

The problem occurred in a test suite. There I removed the TCP layer and connected my client directly to the server. Basically, the interface is abstract using event kind of communication that then in "real" is fulfilled by a TCP connection. 

I use interface.emit(data) to send and interface.on('data', (data)=>{...}) to receive the data. So in the test suite at the end of the day, there is no async communication because there are no blocking calls.

Since I wanted to ensure that the Bufferers received are proper JSON buffers the Parser was implemented as a gatekeeper in the interface ...

**Comment by jahnestacado** [comment]
@martin-tauber Made the change and published new module version 1.0.9

You can find a basic example [here](https://head-detached.com/blog/57543028a5f6be510742a8bb/chunk2json-json-stream-parsing-without-delimeters)

**Comment by martin-tauber** [comment]
Hi Ioannis,

thanks for closing the „bug“. I will test it ASAP. BTW which Corba library are you working on? I’m asking since the project I am working on is also some dealing with remote objects …

Regards
Martin

**Comment by jahnestacado** [comment]
Hi Martin,
The CORBA lib that I am referring too is not opensourced/commercial. It has been built in-house so it is not available outside the company.

Regards,
Ioannis
